branches:
  only:
    - main
language: node_js
node_js:
  - 12

services:
  - docker

script:
  ## Build docker
  - docker-compose -f docker-compose-build.yaml build
  ## Tagging
  - docker tag udagram-api-feed revir216/udagram-api-feed
  - docker tag udagram-api-user revir216/udagram-api-user
  - docker tag udagram-frontend revir216/udagram-frontend
  - docker tag reverseproxy revir216/reverseproxy
  ## Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io
  - docker push revir216/udagram-api-feed
  - docker push revir216/udagram-api-user
  - docker push revir216/udagram-frontend
  - docker push revir216/reverseproxy

